version: '3'

services:
  product-service: #API
    build: ./admin-api
    volumes:
      - ./admin-api:/usr/src/api
    ports:
      - 5001:8080
    depends_on:
      - mongo

  website: #web site
    build: ./web-page
    volumes:
      - ./web-page:/usr/src/web
    ports:
      - 5000:80
    depends_on:
      - product-service

  mongo: #mongoDb
    image: mongo:latest
    ports:
      - '27017:27017'